# Generated by Django 6.0 on 2025-12-18 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Original text description of the scene')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryboardPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_number', models.IntegerField()),
                ('description', models.TextField(help_text='Description of this panel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='storyboard_panels/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or direction for this panel')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='storyboard.storyboard')),
            ],
            options={
                'ordering': ['panel_number'],
                'unique_together': {('storyboard', 'panel_number')},
            },
        ),
    ]
