# Generated by Django 6.0 on 2025-12-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyboardpanel',
            name='image_prompt',
            field=models.TextField(blank=True, default='', help_text='Prompt that will be sent to Stability AI for this panel'),
        ),
        migrations.AddField(
            model_name='storyboardpanel',
            name='prompt_approved',
            field=models.BooleanField(default=False, help_text='Whether the prompt has been reviewed by the user'),
        ),
    ]
