# Generated by Django 6.1.1 on 2026-09-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0002_storyboardpanel_image_prompt_prompt_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyboard',
            name='description',
            field=models.TextField(help_text='Original text description of the scene', max_length=10000),
        ),
        migrations.AlterField(
            model_name='storyboardpanel',
            name='description',
            field=models.TextField(help_text='Description of this panel', max_length=2000),
        ),
        migrations.AlterField(
            model_name='storyboardpanel',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='Prompt that will be sent to Stability AI for this panel', max_length=2000),
        ),
        migrations.AlterField(
            model_name='storyboardpanel',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or direction for this panel', max_length=1000),
        ),
    ]
